### ISSUE TITLE
"Missing Registry" error using Ledger Migration App on People Chain

### ISSUE THREAD

**Issue by filippoweb3** [TalismanSociety/talisman#1502]
When I try to remove my identity or add a proxy on People Chain using a Ledger account imported through the Migration App, I get the error "Missing Registry" on the extension

**Comment by chidg** [comment]
Hi @filippoweb3 , 
how is the extrinsic constructed? Has the dapp you're using (assuming you're using a dapp) been updated with the latest polkadot.js api library?

**Comment by filippoweb3** [comment]
hey the dapp is Polkadot JS UI, updated
I think this PR will fix the issue https://github.com/polkadot-fellows/runtimes/pull/371, apparently there was some missing stuff for People Chain on Kusama

**Comment by chidg** [comment]
Will leave this open, please let us know if that solves it.

**Comment by 0xKheops** [comment]
I can reproduce easily.

Error occurs because Talisman doesn't know about this chain, so it doesn't know any rpc to fetch metadata from.
Error is handled gracefully so no actual bug there.

![image](https://github.com/TalismanSociety/talisman/assets/26880866/caf9aaeb-9116-4707-a7a5-4336f7289b96)
![image](https://github.com/TalismanSociety/talisman/assets/26880866/8aecfef5-2ea3-4f95-a1be-3d3a91514395)

We just need to register that chain in chaindata.

Thank you @filippoweb3 for the heads up!

**Comment by chidg** [comment]
Hi @filippoweb3 , People Chain has now been added to our chaindata config - please let us know if this problem is solved.
