### ISSUE TITLE
Issues importing Polkadot ledger accounts with specific address index

### ISSUE THREAD

**Issue by fgimenez** [TalismanSociety/talisman#1524]
**Describe the bug**
I'm trying to import Polkadot accounts from ledger that have the account type (first derivation level) set to 0 but the account index (second derivation level) set to different values. They don't show up in the import list, is it possible to import them?

**Screenshots**
This is how I imported the accounts in polkadot-js, note that the second selector has a non-zero value.

![Screenshot from 2024-07-06 19-58-41](https://github.com/TalismanSociety/talisman/assets/70376/a022364e-de25-47bc-a269-efadd7272ec3)

**Comment by chidg** [comment]
Hi @fgimenez ,
currently Talisman only supports Ledger import by incrementing through the account index in order to be compatible with Legder Live. 

We do have some work in progress to enable full customisation of both parameters when importing though, which was completed in https://github.com/TalismanSociety/talisman/pull/1516 - we intended to release this last week, but found some bugs at the last minute, so keep an eye out for https://github.com/TalismanSociety/talisman/pull/1523 - it's a priority for us this week.

Relabelling as feature request rather than bug.
Closed by https://github.com/TalismanSociety/talisman/pull/1523.
